services:

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arthur-red_wire
      MYSQL_USER: dev
      MYSQL_PASSWORD: "1234"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /var/www/html/vendor
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      DATABASE_URL: "mysql://dev:1234@database:3306/arthur-red_wire?serverVersion=8.0.32&charset=utf8mb4"
      APP_ENV: dev
      APP_SECRET: "unsecretlocalpourdev1234567890ab"
      JWT_PASSPHRASE: ""
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data: